#!/bin/bash

# Check if an argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: makepost <postname>"
    exit 1
fi

postname="$1"
date=$(date +'%Y-%m-%d')
filename="content/posts/${date}_${postname}.md"

# Template content
template="+++
title = \"${postname}\"
date = ${date}
+++

This is ${postname}'s content."

# Create the Markdown file with template content
echo -e "${template}" > "$filename"

echo "Created new post: $filename"
